### ISSUE TITLE
KITTI val result

### ISSUE THREAD

**Issue by DezeZhao** [xmuqimingxia/3D-HANet#2]
<img width="750" alt="image" src="https://user-images.githubusercontent.com/44592986/232553984-4b64ccfc-0688-4615-b803-2c01760a9282.png">

hi @xmuqimingxia , I am interested in your work. Are the results above `Car` detection results? It seemed that you didn't point out it. paper only says, "The detection intersection over union (IoU) thresholds are set to 0.7, 0.5, and 0.5, respectively, and the recall points are 40." And I am confused about whether 0.7, 0.5, 0.5 corresponds to SASSD, SECOND and PointPillars respectively. 

Assume that the results are Car results, I think 3D detection results may not be so low as 73.48 in moderate level on SECOND model?

**Comment by xmuqimingxia** [comment]
Thank you very much for your attention and reminder. There was indeed an error in the writing of our IOU threshold settings. The experimental settings based on SASSD were conducted at a lower IOU threshold. However, the experimental results of SECOND and PointPillars were obtained with threshold settings of 0.7, 0.5, and 0.5. Additionally, as mentioned in the paper, in order to achieve better accuracy, we did not use the original version of SECOND, but instead incorporated some of the techniques from SASSD into SECOND. The reason for the unsatisfactory performance of SECOND in the table may be due to insufficient training. Our SECOND model was trained on 1 * 1080TI, but the experimental environment for comparison was the same, so we believe the experimental results are relatively fair.

**Comment by DezeZhao** [comment]
OK, thank you for your early reply. I get it now.
